name: Release
on: [push]

jobs:
  win-build:
    name: Windows Build App
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build:app-win # will run `yarn build:app` command

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            app-src/dist/*.exe
